import type { ComponentType } from "react";
import type { LabExperiment } from "../types";
import { AttentionLensArchiveClock } from "../archive/IndependentArchiveClocks";
import {
  AttentionLensCoherentClock,
  AttentionLensDoubleCrestClock,
  AttentionLensForwardClock,
  AttentionLensLocalClock,
  AttentionLensPulseClock,
  AttentionLensTwinClock,
} from "./AttentionLensStudies";

export const attentionLensStudies: LabExperiment[] = [
  {
    id: 727,
    slug: "attention-lens-727-original-study",
    nameEn: "Attention Lens · Original",
    description: "原版 Attention Lens：秒针只扭曲六十枚刻度，数字和时分针仍留在正常圆盘。",
    mechanism: "刻度围绕秒针做 25° 正弦角度扭曲；十二数字、时针和分针保持经典位置。",
    reading: "仍可按正常数字与时分针读取，红秒针附近的刻度获得更多空间。",
    status: "727 study · original",
    position: 727,
    batch: 9,
  },
  {
    id: 737,
    slug: "attention-lens-737-coherent",
    nameEn: "Illusion",
    description: "秒针扭曲整套角度空间：刻度、数字、时针和分针一起移动。",
    mechanism: "以秒针为透镜中心，对任意真实角度使用同一正弦映射；数字跟随主刻度，时针和分针指向各自被扭曲后的正确刻度。",
    reading: "不能按正常圆盘读时；先接受墨黑刻度空间的扭曲，再沿黑色时分针读取其中的对应位置。",
    status: "selected as #034 Illusion",
    position: 737,
    batch: 9,
  },
  {
    id: 740,
    slug: "attention-lens-740-local-focus",
    nameEn: "Attention Lens · Local Focus",
    description: "扭曲被限制在秒针附近，远处圆周几乎恢复均匀。",
    mechanism: "所有角度共享局部高斯映射；秒针附近的刻度和数字被放大，影响随角距离快速衰减，时分针同步指向变形后的正确位置。",
    reading: "黑色时分针仍指向局部放大后的墨黑刻度；远离秒针处接近正常圆盘。",
    status: "727 study · local lens",
    position: 740,
    batch: 9,
  },
  {
    id: 741,
    slug: "attention-lens-741-forward-bias",
    nameEn: "Attention Lens · Forward Bias",
    description: "秒针前方与后方拥有不同的拉伸速度，圆盘产生明确方向感。",
    mechanism: "在 30° 主正弦透镜上叠加 15° 单向偏置项；刻度、数字和黑色时分针共享同一非对称映射。",
    reading: "沿秒针运动方向观察前后不对称的墨黑刻度，再读取同步偏转的时分针。",
    status: "727 study · asymmetric lens",
    position: 741,
    batch: 9,
  },
  {
    id: 742,
    slug: "attention-lens-742-double-crest",
    nameEn: "Attention Lens · Double Crest",
    description: "一阶与二阶角度波制造清晰的主峰、肩部与压缩谷。",
    mechanism: "所有角度共享 42° 一阶正弦和 15° 二阶正弦叠加；映射保持单调，但圆周疏密出现比 #737 更强的双层结构。",
    reading: "沿黑色时分针读取双层疏密刻度；数字始终贴着对应主刻度。",
    status: "727 study · double crest",
    position: 742,
    batch: 9,
  },
  {
    id: 743,
    slug: "attention-lens-743-pulse",
    nameEn: "Attention Lens · Pulse",
    description: "整套角度空间每秒从轻微扭曲呼吸到强烈扭曲，再回落。",
    mechanism: "同步正弦透镜的强度在每秒内连续从 12° 增至 38° 后返回；刻度、数字和时分针一同呼吸。",
    reading: "在持续脉动的墨黑刻度空间中读取同步移动的黑色时分针。",
    status: "727 study · breathing lens",
    position: 743,
    batch: 9,
  },
  {
    id: 744,
    slug: "attention-lens-744-twin-focus",
    nameEn: "Attention Lens · Twin Focus",
    description: "秒针与其正对面同时形成两个舒展区，圆周成为双焦透镜。",
    mechanism: "使用 20° 二阶正弦映射，使秒针方向和 180° 对侧同时扩张；数字、刻度与时分针共享该双焦坐标系。",
    reading: "在两个相对的墨黑舒展区之间读取黑色时分针。",
    status: "727 study · twin focus",
    position: 744,
    batch: 9,
  },
];

export const attentionLensStudyComponents: Record<number, ComponentType> = {
  727: AttentionLensArchiveClock,
  737: AttentionLensCoherentClock,
  740: AttentionLensLocalClock,
  741: AttentionLensForwardClock,
  742: AttentionLensDoubleCrestClock,
  743: AttentionLensPulseClock,
  744: AttentionLensTwinClock,
};