import type { LabExperiment } from "../types";

const entries = [
  [1020, "melt", "Melt", "整只 #001 像受热的唱片向下融化，数字、刻度与三针一起流淌，但针尖仍指向真实时间。"],
  [1021, "fisheye", "Fisheye", "一枚沿秒针移动的巨大凸透镜把经过处的刻度、数字与指针局部夸张放大。"],
  [1022, "corkscrew", "Corkscrew", "从表心到盘缘的空间被拧成螺旋，三根原始指针也随半径连续扭曲。"],
  [1023, "ripple", "Ripple", "秒针每走一步便在钟面上激起同心波，六十刻度和十二数字随波峰反复起伏。"],
  [1024, "pinch", "Pinch", "分钟方向像一只无形的手捏住钟面，将圆盘压成不断转向的狭长形。"],
  [1025, "rubber", "Rubber", "表盘像橡胶膜一样在横向拉伸、纵向回缩，三针随整张膜夸张呼吸。"],
  [1026, "quadrant-twist", "Quadrant Twist", "钟面四个象限朝相反方向扭转，十二数字在四条接缝处持续错位又接合。"],
  [1027, "wave-rim", "Wave Rim", "原本平静的圆周长出十二道巨浪，数字坐在波峰上，指针在波动边界内照常报时。"],
  [1028, "implosion", "Implosion", "每到整秒，整只 #001 从盘缘向表心猛烈坍缩，再迅速弹回原尺寸。"],
  [1029, "liquefy", "Liquefy", "钟面被切成许多竖向液柱，数字与指针随列波左右摇晃，像一面正在融化的镜子。"],

  [1030, "rgb-split", "RGB Split", "#001 的时、分、秒各自裂成红绿蓝三道错位光影，重叠处重新变成白光。"],
  [1031, "cmyk-ghost", "CMYK Ghost", "青、品红、黄、黑四张完整钟面轻微错版，形成不断漂移的印刷幻影。"],
  [1032, "complement", "Complement", "钟面与指针每秒交换一次互补色，熟悉的黑白红在色轮两端来回翻转。"],
  [1033, "spectrum", "Spectrum", "六十枚刻度组成完整光谱，色环绕着仍然准确的黑色时分针持续流动。"],
  [1034, "neon", "Neon", "#001 被点亮成高饱和霓虹管，三针拖着不同颜色的辉光穿过深色钟面。"],
  [1035, "solarized", "Solarized", "表盘被压成少数几档极端色阶，色阶边界随秒针扫过而突然翻面。"],
  [1036, "heat-map", "Heat Map", "靠近三根针尖的数字和刻度被加热成黄白色，远处则退入蓝紫冷区。"],
  [1037, "acid-wash", "Acid Wash", "一层不断翻滚的酸性色云穿过 #001，钟面构件在强烈色差中保持原始位置。"],
  [1038, "color-eclipse", "Color Eclipse", "两枚巨大彩色圆影沿时针和分针方向横越表盘，重叠处产生第三种颜色。"],
  [1039, "chromatic-aberration", "Chromatic Aberration", "整只 #001 分裂成三张红绿蓝色版，色版随秒相位错开又短暂重合。"],

  [1040, "echo-hands", "Echo Hands", "每根指针身后保留一串逐渐淡去的旧位置，时间像有惯性一样拖过钟面。"],
  [1041, "clock-tunnel", "Clock Tunnel", "六只递归缩小的 #001 向表心坠落，每一层都显示同一时刻却拥有不同相位。"],
  [1042, "kaleidoscope", "Kaleidoscope", "三根指针被六面镜复制成放射花形，真实的一组仍以黑黑红从镜像中浮现。"],
  [1043, "double-vision", "Double Vision", "两张完整 #001 在秒的节拍里左右分离，重影中心只有短暂瞬间完全重合。"],
  [1044, "orbiting-faces", "Orbiting Faces", "十二只微缩 #001 沿主表盘外围公转，中央原钟仍保持清楚而稳定。"],
  [1045, "phase-choir", "Phase Choir", "十二组时分秒针以不同相位同时演奏，真实三针用最高对比度压住整片合唱。"],
  [1046, "persistence-fan", "Persistence Fan", "最近一秒内的多个指针姿态被同时保留，三针展开成半透明扇面。"],
  [1047, "shutter-wheel", "Shutter Wheel", "十二枚旋转快门片交替露出正常与转动后的 #001，钟面像被切换成两个现实。"],
  [1048, "clock-bloom", "Clock Bloom", "时针与分针被复制成十二组花瓣，真实针尖在这朵机械花中继续准确报时。"],
  [1049, "infinite-twelve", "Infinite Twelve", "数字 12 沿螺旋不断缩小坠入中心，原来的十二个小时数字仍守在最外圈。"],

  [1050, "strobe-second", "Strobe Second", "每个整秒的开头，整只 #001 短暂爆闪成反相高饱和色，然后退回纸面。"],
  [1051, "numeral-wave", "Numeral Wave", "十二个小时数字被秒针依次击中，像观众席人浪一样夸张放大再落下。"],
  [1052, "tick-pulse", "Tick Pulse", "秒针经过的刻度会骤然变粗变长，一圈脉冲紧贴着红针绕表盘奔跑。"],
  [1053, "alternating-reality", "Alternating Reality", "每半秒钟面便在正常与负片现实之间切换，三针的位置始终不变。"],
  [1054, "frame-skip", "Frame Skip", "红秒针故意在一个整秒内部跳到三个互相冲突的位置，下一秒才重新对齐。"],
  [1055, "flashback", "Flashback", "当前秒针清晰存在，上一秒的位置却会在每次跳秒后突然闪回一次。"],
  [1056, "lightning-dial", "Lightning Dial", "笔直秒针被折成一道锯齿闪电，抵达刻度时让整条径向瞬间发亮。"],
  [1057, "breathing-face", "Breathing Face", "每一秒钟面都剧烈吸气与吐气，圆周、数字和三针一起胀缩。"],
  [1058, "color-beat", "Color Beat", "一秒被切成四拍，钟面背景在四种刺眼颜色之间有节制地闪换。"],
  [1059, "afterimage-burst", "Afterimage Burst", "每次整秒都会从红针位置炸开一圈彩色残像，随后在下一秒前迅速消散。"],

  [1060, "vortex-hands", "Vortex Hands", "三根直针被卷成螺旋曲线，只有远端仍准确落在 #001 的真实刻度上。"],
  [1061, "melting-numerals", "Melting Numerals", "十二个 Georgia 数字像湿墨一样向下拉长，滴落幅度按秒波浪依次传递。"],
  [1062, "prism-core", "Prism Core", "三根针穿过表心棱镜后折成多道彩光，但每束主光仍指向正确时间。"],
  [1063, "fragmented-face", "Fragmented Face", "#001 被切成十二枚扇片，每片独立旋转、缩放和变色，却仍拼回同一只钟。"],
  [1064, "moire-halo", "Moiré Halo", "两层密集辐线在表缘反向旋转，生成翻滚的摩尔光环包围原始三针。"],
  [1065, "magnetic-numerals", "Magnetic Numerals", "十二个数字围绕各自锚点疯狂绕圈，靠近秒针时又被无形磁场猛然吸走。"],
  [1066, "sine-hands", "Sine Hands", "时分秒三根针变成高振幅正弦波，波尾精确落在原来的针尖位置。"],
  [1067, "polarized", "Polarized", "一枚旋转偏振片让钟面扇区交替变亮、变暗和变色，真实三针穿过所有层。"],
  [1068, "hallucination", "Hallucination", "三圈重复数字以不同方向和速度摇晃，观看者在多重 1–12 中寻找真实刻度。"],
  [1069, "psychedelic-001", "Psychedelic 001", "#001 的圆面、数字、刻度和三针同时进入波形、分色、复像与脉冲的最大化状态。"],
] as const;

const tripleEclipseEntries: LabExperiment[] = [
  {
    id: 1070,
    slug: "round-1020-1070-triple-eclipse-spring",
    nameEn: "Triple Eclipse · Spring",
    description: "樱粉、晴蓝与淡黄三圆分别围绕时针、分针、秒针；原表盘只在三圆覆盖处显现。",
    mechanism: "三圆圆心位于对应针尖，半径等于该针从尾端到针尖的完整长度；低饱和颜色以正片叠底混合。",
    reading: "三针保持 #001 的标准读法；圆内可见的边缘、刻度与数字帮助确认方向。",
    status: "round 1020 · triple eclipse palette",
    position: 1070,
    batch: 11,
    face: "none",
  },
  {
    id: 1071,
    slug: "round-1020-1071-triple-eclipse-sky",
    nameEn: "Triple Eclipse · Sky",
    description: "天蓝、薄荷绿与浅珊瑚三圆跟随针尖，在透明背景上轻柔交叠。",
    mechanism: "几何与 Spring 版完全一致，以清新的冷暖配色形成交叠区。",
    reading: "黑色刻度和数字只在任意圆内出现；#001 三针完整保留。",
    status: "round 1020 · triple eclipse palette",
    position: 1071,
    batch: 11,
    face: "none",
  },
  {
    id: 1072,
    slug: "round-1020-1072-triple-eclipse-sorbet",
    nameEn: "Triple Eclipse · Sorbet",
    description: "杏橙、淡紫与水绿三圆像雪葩色块一样叠合，表盘碎片随针尖游移。",
    mechanism: "三圆保持固定真实尺寸，以清淡的橙紫绿色形成柔和交集。",
    reading: "标准黑黑红三针按 #001 读时；表盘构件只在圆域内可见。",
    status: "round 1020 · triple eclipse palette",
    position: 1072,
    batch: 11,
    face: "none",
  },
  {
    id: 1073,
    slug: "round-1020-1073-triple-eclipse-garden",
    nameEn: "Triple Eclipse · Garden",
    description: "嫩叶绿、矢车菊蓝与浅玫瑰三圆构成清新的花园色域。",
    mechanism: "三圆以低饱和绿蓝粉正片叠合，遮罩规则与真实尺寸保持不变。",
    reading: "标准三针完整显示，圆内显露原始刻度与数字。",
    status: "round 1020 · triple eclipse palette",
    position: 1073,
    batch: 11,
    face: "none",
  },
  {
    id: 1074,
    slug: "round-1020-1074-triple-eclipse-morning",
    nameEn: "Triple Eclipse · Morning",
    description: "晨蓝、柔黄与浅珊瑚三圆在透明背景上叠合，形成明亮的清晨配色。",
    mechanism: "以清淡蓝黄红正片叠底，保留明确的三圆重叠边界。",
    reading: "深色时分针与红秒针按 #001 读取，表盘只在三圆并集内出现。",
    status: "round 1020 · triple eclipse palette",
    position: 1074,
    batch: 11,
    face: "none",
  },
  {
    id: 1075,
    slug: "round-1020-1075-triple-eclipse-petal",
    nameEn: "Triple Eclipse · Petal",
    description: "花瓣粉、浅薰衣草与海沫绿三圆轻柔穿透，保持最淡雅的综合色。",
    mechanism: "三圆使用粉紫绿低饱和正片叠色，尺寸仍由标准三针线段决定。",
    reading: "黑色刻度与数字在圆内浮现；标准黑黑红三针完整可见。",
    status: "round 1020 · triple eclipse palette",
    position: 1075,
    batch: 11,
    face: "none",
  },
  {
    id: 1076,
    slug: "round-1020-1076-triple-eclipse-classic",
    nameEn: "Triple Eclipse · Classic",
    description: "黑、灰、红三圆沿用项目经典色彩，在无底色的表面上揭开 #001。",
    mechanism: "时针圆为黑、分针圆为灰、秒针圆为红；三圆几何与其他版本完全一致。",
    reading: "黑色时针、黑色分针与红色秒针保持 #001 原样；表盘只在三圆并集内可见。",
    status: "round 1020 · triple eclipse palette",
    position: 1076,
    batch: 11,
    face: "none",
  },
];

export const round1020Studies: LabExperiment[] = [...entries.map(([
  id,
  slug,
  nameEn,
  description,
]): LabExperiment => ({
  id,
  slug: `round-1020-${id}-${slug}`,
  nameEn,
  description,
  mechanism: "以 #001 Classic Round 的圆面、十二数字、六十刻度与三针为唯一原本，对其施加强烈的迷幻视觉变换。",
  reading: "仍按 #001 读取时针、分针与红色秒针；变形、颜色与闪烁不改变真实针尖的时间关系。",
  status: "round 1020 · psychedelic study",
  position: id,
  batch: 11,
  face: "none",
})), ...tripleEclipseEntries];
